apiVersion: v1
kind: Namespace
metadata:
  name: ns-elasticsearch
  labels:
    name: ns-elasticsearch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: ns-elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-elasticsearch
  nfs:
    path: /public/elasticsearch
    server: 192.168.0.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: ns-elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-elasticsearch
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch-data
  namespace: ns-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      elastic-app: elasticsearch
  template:
    metadata:
      labels:
        elastic-app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-data
          image: elasticsearch:7.9.0
          #lifecycle:
           # postStart:
           #   exec:
           #     command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"]
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elasticsearch
              mountPath: /usr/share/elasticsearch/data
          env:
            #- name: "cluster.name"
            #  value: "elasticsearch-cluster"
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
 
      volumes:
        - name: elasticsearch
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch-service
  name: elasticsearch-service
  namespace: ns-elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: "9200"
      nodePort: 30301
    - port: 9300
      name: "9300"
      targetPort: 9300
      nodePort: 30302
  selector:
    elastic-app: elasticsearch
  type: NodePort
