kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    elastic-app: logstash
  name: logstash
  namespace: ns-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      elastic-app: logstash
  template:
    metadata:
      labels:
        elastic-app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.9.0
         # volumeMounts:
         #   - mountPath: /usr/share/logstash/pipeline
         #     name: logstash-conf-volume
          ports:
            - containerPort: 5044
            - containerPort: 5000
              protocol: TCP
            - containerPort: 5000
              protocol: UDP
            - containerPort: 9600
          env:
            - name: "LS_JAVA_OPTS"
              value: "-Xmx256m -Xms256m"
            - name: "http.host"
              value: "0.0.0.0"
            - name: "xpack.monitoring.elasticsearch.hosts"
              value: "http://elasticsearch-service:9200"
            - name: "xpack.monitoring.enabled"
              value: "true"
     # volumes:
     #   - name: logstash-conf-volume
     #     persistentVolumeClaim:
     #       claimName: logstash-pvc

---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: logstash
  name: logstash-service
  namespace: ns-elasticsearch
spec:
  ports:
    - port: 5044
      targetPort: 5044
      nodePort: 30304
      name: "5044"
    - port: 5000
      targetPort: 5000
      nodePort: 30305
      name: "5000"
    - port: 9600
      targetPort: 9600
      nodePort: 30306
      name: "9600"
  selector:
    elastic-app: logstash
  type: NodePort
